syntax = "proto3";
package gameservice;

//心跳
message PingPang {
	uint64 timestamp = 1;	//时间戳
}

//返回结果
message ResponseBase {
  uint32 result = 1;
  string message = 2;
}

//用户信息
message UserInfoAck {
  uint64 playerid = 1;    //玩家Id
  string displayname = 2; //用于显示的数字ID
  string imgurl = 3;      //头像
  string nickname = 4;    //昵称
  int64 diamond = 5;      //金币
  int32 pos = 6;          //位置
  uint32 vipLevel = 7;

}

//登录 gameservice.login
message LoginReq {
  string userid = 1;  //用户ID
  string token = 2;   //登录服拿到的token
}

message LoginAck {
  ResponseBase result = 1;
  UserInfoAck userinfo = 2;   //用户信息
  repeated Free frees = 3;    //下注免费信息
  repeated int32 betOption = 4; // 下注选项
  repeated int64 jpMub = 5;//jp倍数
  repeated PlayerTask playerTasks = 6; //玩家全部下注任务情况
  repeated TaskInfo tasks = 7;         //全部任务
}
message Free {
  int64 amount = 1;     //下注倍数
  int64 freeCount = 2;  //免费次数
  int64 freePool = 3;   //免费奖池
}

//下注   gameservice.call
message CallReq {
  int64 amount = 1;     //金额
}

message Card {
  repeated int32 cards = 1;
}

message XianInfo {
  int32 card = 1;     //中奖的牌
  int32 len = 2;      //线的长度
  int32 multiple = 3; //线倍数(单个的)
  int32 ref = 4;      //线位置
}

message CallAck {
  ResponseBase result = 1;
  UserInfoAck userinfo = 2;         //用户信息
  repeated Card cards = 3;          //牌组(是个3*6的二维数组因为pb协议不支持二维数组)
  repeated XianInfo xiannum = 4;     //线的数量1 第一个 2第二个 3第三个
  int32 mianfeinum = 5;             //免费次数  (剩余的免费次数)
  int32 rewardtype = 6;             //奖励类型 (1:正常金币奖励, 2:免费次数奖励)
  int64 freePool = 7;               //免费奖池 (这一轮后三叶草免费奖池)
  int32  execNum = 8;               //执行次数
  int32 addFgCount = 9;             //在fg中增加Fg次数
  int64 jpWin = 10;
  PlayerTask playerTask = 11;       //玩家任务情况
}

//货币更新广播(非游戏行为) gameservice.updatecoinnotify
message UpdateCoinNotify {
  int64 diamond = 1;  // 剩余数量
  int32 reason = 2;   // 原因 1:支付; 其他：未知
}

message PlayerTask {
  int64 Bet = 1;
  int32 Id = 2;
  int32 Count = 3;
}

message TaskInfo {
  int32 Id = 1;
  int32 Cards = 2;
  int32 Count = 3;
  int32 Reward = 4;
}

//下注   gameservice.claimtaskreward
message ClaimTaskRewardReq {
  int64 bet = 1;     //下注金额
}

message ClaimTaskRewardAck {
  ResponseBase result = 1;
  UserInfoAck userinfo = 2;         //用户信息
  int64  RewardCoin = 3;            //领取金币
}

//下注   gameservice.getranking
message GetRankingReq {
  int64 bet = 1;     //下注金额
}

message GetRankingAck {
  ResponseBase result = 1;
  repeated RankingData  infos = 2;            //排行榜信息
}

message RankingData {
  int64 time = 1;       //时间
  int64 TotalBet = 3;   //总下注金额
  int32 types = 4;      //类型
  string nickname = 5;  //昵称
  string HeadUrl = 6;   //头像地址
}